left_motor_pwm: 13
right_motor_pwm: 12
motor_pwm_frequency: 1000

left_motor_direction_a: 16
left_motor_direction_b: 26
right_motor_direction_a: 5
right_motor_direction_b: 6

left_encoder_channel_a: 17
left_encoder_channel_b: 27
right_encoder_channel_a: 24
right_encoder_channel_b: 23

pulses_per_revolution: 11
gearbox_reduction_ratio: 46
wheel_radius: 0.0335
track_width: 0.2185

control_loop_frequency: 50
kp: 1.0
ki: 0.0
kd: 0.0